version: '3'
# 定义服务，即需要运行的容器集合
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    # 定义该服务所依赖的其他服务，它们将按照依赖顺序启动
    depends_on:
      - mysql-container
      - redis-container
    # 定义项目环境变量
    environment:
      - NODE_ENV=prod
    ports:
      - '3000:3000'
    networks:
      - common-network

  # 定义一个名为'mysql-container'的服务，使用mysql镜像
  mysql-container:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    # 数据卷配置，用于持久化存储
    volumes:
      - /home/Unusual-server/mysql/log:/var/log
      - /home/Unusual-server/mysql/data:/var/lib/mysql
      # - /home/Unusual-server/mysql/conf.d:/ect/mysql/conf.d
      # 初始执行的SQL文件，可用于初始化数据库
      # - /home/Unusual-server/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: us
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # 设置容器时区
      TZ: 'Asia/Shanghai'
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    networks:
      - common-network

  # 定义一个名为'redis-container'的服务，使用redis镜像
  redis-container:
    image: redis
    # 初始配置密码
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - '6379:6379'
    # 数据卷配置，用于持久化存储
    volumes:
      - /home/Unusual-server/redis:/data
    networks:
      - common-network
# 创建网络桥
networks:
  common-network:
    driver: bridge
